Lab 1 is done
IMZolin/Computer-graphics pull request #1
Opened 2024-02-11 10:03 UTC by IMZolin

2024-02-11 19:24 UTC, anthark requested changes
Креативно =) Но Release не компилируется =(

2024-02-12 07:37 UTC, IMZolin commented
Release поправил, также убрал варнинги.

2024-02-12 12:24 UTC, anthark approved these changes
Есть пара замечаний по эффективности, но поскольку задача решена - засчитано =)

2024-02-12 12:24 UTC, anthark commented on lab1/lab1/renderer.cpp
> +    sd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL;
Это не максимально эффективный флаг, лучше использовать FLIP_DISCARD

2024-02-12 12:24 UTC, anthark commented on lab1/lab1/renderer.cpp
> +    sd.BufferDesc.RefreshRate.Numerator = 60;
Здесь можно огрести проблем, поскольку реально у мониторов обычно 5997/100

2024-02-12 12:24 UTC, merged